routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//agregamos los siguientes controladores
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ParqueoController;
use App\Http\Controllers\OperadorController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\EspacioController;
use App\Http\Controllers\AsignacionController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ReclamoController;
use App\Http\Controllers\HistorialReclamoController;
use App\Http\Controllers\ConvocatoriaController;

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('paginaInicio2');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home-operador', [App\Http\Controllers\HomeOperadorController::class, 'index'])->name('home-operador');
Route::get('/abrir-modal', [App\Http\Controllers\ConvocatoriaController::class, 'show'])->name('abrir-modal');

//y creamos un grupo de rutas protegidas para los controladores
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('clientes', ClienteController::class);
    Route::resource('blogs', BlogController::class);
    
    Route::resource('parqueos', ParqueoController::class);
    Route::resource('espacios', EspacioController::class);
    Route::resource('operador', OperadorController::class);
    Route::resource('pagos', PagoController::class);
    Route::resource('asignaciones', AsignacionController::class);

    Route::post('/procesar-pago', [PagoController::class, 'procesarPago'])->name('procesar_pago');
    Route::resource('reclamos', ReclamoController::class);
    Route::resource('historial', HistorialReclamoController::class);
    Route::resource('convocatorias', ConvocatoriaController::class);
    
});





//Route::get('/cliente', [App\Http\Controllers\ClienteController::class, 'login'])->name('login');

app/Models/Convocatoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Convocatoria extends Model
{
    use HasFactory;
    protected $table = 'convocatorias';
    protected $fillable = ['titulo', 'descripcion', 'fecha_inicio', 'fecha_limite', 'imagen'];

}

app/Http/Controllers/ConvocatoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Models\Convocatoria;

class ConvocatoriaController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:ver-convocatoria|crear-convocatoria|editar-convocatoria|borrar-convocatoria',['only' => ['index']]);
         $this->middleware('permission:crear-convocatoria', ['only' => ['create','store']]);
         $this->middleware('permission:borrar-convocatoria', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Con paginación
        $convocatorias = Convocatoria::paginate(5);
        return view('convocatorias.index', compact('convocatorias'));

        //al usar esta paginacion, recordar poner en el el index.blade.php este codigo  {!! $usuarios->links() !!}
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('convocatorias.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required',
            'descripcion' => 'required',
            'fecha_inicio' => 'required|date|after:today',
            'fecha_limite' => 'required|date|after:today',
            'imagen' => 'required|image|mimes:jpeg,png,svg|max:1024',
        ]);

        $convocatoria = $request->all();

        if ($imagen = $request->file('imagen')) {
            $rutaGuardarImg = 'imagen/';
            $imagenParqueo = date('YmdHis') . "." . $imagen->getClientOriginalExtension();
            $imagen->move($rutaGuardarImg, $imagenParqueo);
            $convocatoria['imagen'] = "$imagenParqueo";
        }

        Convocatoria::create($convocatoria);
        return redirect()->route('convocatorias.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Convocatoria $convocatoria)
    {
        return view('convocatorias.vista', compact('convocatoria'));
    }
    public function metodoVista()
    {
        return view('convocatorias.vista');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $convocatoria = Convocatoria::find($id);
    
        return view('convocatorias.editar',compact('convocatoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Convocatoria $convocatoria)
    {
        $request->validate([
            'titulo' => 'required', 
            'descripcion' => 'required',
            'fecha_inicio' => 'required|date', 
            'fecha_limite' => 'required|date',           
        ]);
         $prod = $request->all();
         if($imagen = $request->file('imagen')){
            $rutaGuardarImg = 'imagen/';
            $imagenProducto = date('YmdHis') . "." . $imagen->getClientOriginalExtension(); 
            $imagen->move($rutaGuardarImg, $imagenProducto);
            $prod['imagen'] = "$imagenProducto";
         }else{
            unset($prod['imagen']);
         }
         $convocatoria->update($prod);
         return redirect()->route('convocatorias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Convocatoria $convocatoria)
    {
        $convocatoria->delete();
        return redirect()->route('convocatorias.index');
    }
}

resources/views/convocatorias/crear.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Crear Convocatoria</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">     
                                                                      
                        @if ($errors->any())                                                
                            <div class="alert alert-dark alert-dismissible fade show" role="alert">
                            <strong>¡Revise los campos!</strong>                        
                                @foreach ($errors->all() as $error)                                    
                                    <span class="badge badge-danger">{{ $error }}</span>
                                @endforeach                        
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        @endif

                    <form action="{{ route('convocatorias.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                 <label for="titulo">Título</label>
                                 <input type="text" name="titulo" id="titulo" class="form-control" required>
                              </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">                      
                              <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <textarea name="descripcion" id="descripcion" class="form-control" rows="4" required></textarea>
                              </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <div class="form-group">
                                <label for="fecha_inicio">Fecha Inicio</label>
                                <input type="datetime-local" name="fecha_inicio" id="fecha_inicio" class="form-control" required>
                              </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <div class="form-group">
                                <label for="fecha_limite">Fecha límite</label>
                                <input type="datetime-local" name="fecha_limite" id="fecha_limite" class="form-control" required>
                              </div>
                            </div>

                            <!-- Para ver la imagen seleccionada, de lo contrario no se -->
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <img id="imagenSeleccionada" style="max-height: 150px;">           
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold mb-1">Subir Imagen</label>
                              <div class='flex items-center justify-center w-full'>
                                <label >
                                    <input name="imagen" id="imagen" type='file' class="hidden" />
                               </label>
                              </div>
                            </div>
                            
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Guardar</button>                            
                            
                           </div>
                        </div>
                    </form>
                    
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- Script para ver la imagen antes de CREAR UN NUEVO PRODUCTO -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
<script>   
    $(document).ready(function (e) {   
        $('#imagen').change(function(){            
            let reader = new FileReader();
            reader.onload = (e) => { 
                $('#imagenSeleccionada').attr('src', e.target.result); 
            }
            reader.readAsDataURL(this.files[0]); 
        });
    });
</script>
@endsection

resources/views/convocatorias/editar.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Editar Convocatoria</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">     
                                                                      
                        @if ($errors->any())                                                
                            <div class="alert alert-dark alert-dismissible fade show" role="alert">
                            <strong>¡Revise los campos!</strong>                        
                                @foreach ($errors->all() as $error)                                    
                                    <span class="badge badge-danger">{{ $error }}</span>
                                @endforeach                        
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                        @endif
                    
                        
                    {!! Form::model($convocatoria, ['method' => 'PATCH','enctype'=>'multipart/form-data','route' => ['convocatorias.update', $convocatoria->id]]) !!}
                        
                    @csrf
                    @method('PUT')    
                    
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                 <label for="titulo">Título</label>
                                 <input type="text" name="titulo" id="titulo" class="form-control" value="{{ $convocatoria->titulo }}" required>
                              </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">                      
                              <div class="form-group">
                                <label for="descripcion">Descripción</label>
                                <input name="descripcion" id="descripcion" class="form-control" rows="4" value="{{ $convocatoria->descripcion }}" required>
                              </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <div class="form-group">
                                <label for="fecha_inicio">Fecha Inicio</label>
                                <input type="datetime-local" name="fecha_inicio" id="fecha_inicio" class="form-control" value="{{ $convocatoria->fecha_inicio }}" required>
                              </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <div class="form-group">
                                <label for="fecha_limite">Fecha límite</label>
                                <input type="datetime-local" name="fecha_limite" id="fecha_limite" class="form-control" value="{{ $convocatoria->fecha_limite }}" required>
                              </div>
                            </div>

                            <!-- Para ver la imagen seleccionada, de lo contrario no se -->
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                   <img src="/imagen/{{ $convocatoria ->imagen }}" width="200px" id="imagenSeleccionada">
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                               <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold mb-1">Subir Imagen</label>
                              <div class='flex items-center justify-center w-full'>
                                <label >
                                    <input name="imagen" id="imagen" type='file' class="hidden" />
                               </label>
                              </div>
                            </div>
                            
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Guardar</button>                            
                            
                           </div>
                        </div>
                        {!! Form::close() !!}
                    
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- Script para ver la imagen antes de CREAR UN NUEVO PRODUCTO -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
<script>   
    $(document).ready(function (e) {   
        $('#imagen').change(function(){            
            let reader = new FileReader();
            reader.onload = (e) => { 
                $('#imagenSeleccionada').attr('src', e.target.result); 
            }
            reader.readAsDataURL(this.files[0]); 
        });
    });
</script>
@endsection

resources/views/convocatorias/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Convocatorias</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                        @can('crear-convocatoria')
                           <a class="btn btn-warning" href="{{ route('convocatorias.create') }}">Nueva convocatoria</a>
                        @endcan 
                         <!-- Botón para abrir el modal -->
                        @can('ver-convocatoria')
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#carruselModal">
                            Ver Convocatorias
                        </button>
                        @endcan

                           <table class="table table-striped mt-2">
                              <thead style="background-color:#6777ef">                                     
                                  <th style="display: none;">ID</th>
                                  <th style="color:#fff;">Titulo</th>
                                  <th style="color:#fff;">Descripcion</th>
                                  <th style="color:#fff;">Fecha Inicio</th>
                                  <th style="color:#fff;">Fecha final</th>  
                                  <th style="color:#fff;">Imagen</th>  
                                  <th style="color:#fff;">Opciones</th>                                                                
                              </thead>
                              <tbody>
                                @foreach ($convocatorias as $convocatoria)
                                  <tr>
                                    <td style="display: none;">{{ $convocatoria->id }}</td>
                                    <td>{{ $convocatoria->titulo }}</td>
                                    <td>{{ $convocatoria->descripcion }}</td>
                                    <td>{{ $convocatoria->fecha_inicio }}</td>
                                    <td>{{ $convocatoria->fecha_limite }}</td>
                                    <td>
                                       <img src="/imagen/{{ $convocatoria->imagen }}" width="80L" >

                                    </td>
                                    <td> 
                                    @can('editar-convocatoria')                                
                                      <a class="btn btn-info" href="{{ route('convocatorias.edit',$convocatoria->id) }}">Editar</a>
                                    @endcan
                                     
                                    @can('borrar-convocatoria')
                                      {!! Form::open(['method' => 'DELETE','route' => ['convocatorias.destroy', $convocatoria->id],'style'=>'display:inline']) !!}
                                          {!! Form::submit('Borrar', ['class' => 'btn btn-danger']) !!}
                                      {!! Form::close() !!}
                                    @endcan
                                    

                                    </td>
                                @endforeach
                                      
                                 </tr>
                                </tbody>
                            </table>
                            <!-- Centramos la paginacion a la derecha -->
                          <div class="pagination justify-content-end">
                            {!! $convocatorias->links() !!}
                          </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
<style>
    .carousel-img {
        width: 1100px; /* Ancho deseado */
        height: 500px; /* Alto deseado */
        object-fit: cover; /* Ajuste de imagen */
    }
    .carousel-text {
        color: white; /* Color del texto */
        -webkit-text-stroke: 1px black; /* Borde blanco */
        text-stroke: 1px black; /* Borde blanco */
    }
</style>

<!-- Modal -->
<div class="modal fade" id="carruselModal" tabindex="-1" role="dialog" aria-labelledby="carruselModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="carruselModalLabel">Convocatoria</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Slides del carrusel -->
                    <div class="carousel-inner">
                        @foreach ($convocatorias as $convocatoria)
                            <div class="carousel-item{{ $loop->first ? ' active' : '' }}">
                                <img src="/imagen/{{ $convocatoria->imagen }}"  class="carousel-img">
                                <div class="carousel-caption">
                                    <h3 class="carousel-text">{{ $convocatoria->titulo }}</h3>
                                    <h4 class="carousel-text">{{ $convocatoria->descripcion }}</h4>
                                    <h4 class="carousel-text">{{ $convocatoria->fecha_inicio }}</h4>
                                    <h4 class="carousel-text">{{ $convocatoria->fecha_limite }}</h4>
                                    <!-- Otros datos del objeto -->
                                </div>
                            </div>
                        @endforeach
                    </div>

                    <!-- Controles del carrusel -->
                    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Anterior</span>
                    </a>
                    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Siguiente</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/convocatorias/vista.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Convocatoria</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="">Usuario/Email</label>
                            <input type="text" id="usuario" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="">Contraseña</label>
                            <input type="password" id="password" class="form-control">
                        </div>
                    </div>
                </div>
                <div id="respuesta">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a href="{{ url('/login') }}" class="btn btn-primary text-sm text-gray-700 underline inicioSesion">Registrarse</a>
            </div>
        </div>
    </div>
</div>