routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//agregamos los siguientes controladores
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ParqueoController;
use App\Http\Controllers\OperadorController;
use App\Http\Controllers\PagoController;
use App\Http\Controllers\EspacioController;
use App\Http\Controllers\AsignacionController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ReclamoController;
use App\Http\Controllers\HistorialReclamoController;
use App\Http\Controllers\ConvocatoriaController;

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('paginaInicio2');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home-operador', [App\Http\Controllers\HomeOperadorController::class, 'index'])->name('home-operador');
Route::get('/abrir-modal', [App\Http\Controllers\ConvocatoriaController::class, 'show'])->name('abrir-modal');

//y creamos un grupo de rutas protegidas para los controladores
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('clientes', ClienteController::class);
    Route::resource('blogs', BlogController::class);
    
    Route::resource('parqueos', ParqueoController::class);
    Route::resource('espacios', EspacioController::class);
    Route::resource('operador', OperadorController::class);
    Route::resource('pagos', PagoController::class);
    Route::resource('asignaciones', AsignacionController::class);

    Route::post('/procesar-pago', [PagoController::class, 'procesarPago'])->name('procesar_pago');
    Route::resource('reclamos', ReclamoController::class);
    Route::resource('historial', HistorialReclamoController::class);
    Route::resource('convocatorias', ConvocatoriaController::class);
    
});





//Route::get('/cliente', [App\Http\Controllers\ClienteController::class, 'login'])->name('login');

app/Models/Parqueo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Parqueo extends Model
{
    use HasFactory;

    protected $table = 'parqueos';
    protected $fillable = ['nombre', 'descripcion', 'estado', 'filas', 'columnas', 'cantidadEspacios', 'precio'];
    public function espacios()
    {
        return $this->hasMany(Espacio::class);
    }
}

app/Http/Controllers/ParqueoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Espacio;
use App\Models\Parqueo;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator as FacadesValidator;

class ParqueoController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:ver-parqueo|crear-parqueo|editar-parqueo|borrar-parqueo',['only' => ['index']]);
         $this->middleware('permission:crear-parqueo', ['only' => ['create','store']]);
         $this->middleware('permission:borrar-parqueo', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $parqueos = Parqueo::All();
        $espacios = Espacio::all();
        return view('parqueos.index', compact('parqueos', 'espacios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parqueos = Parqueo::All();
        return view('parqueos.crear', compact('parqueos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Valida los datos del formulario
        $rules = [
            'nombre' => 'required|string|max:255',
            'filas' => 'required|integer|min:1',
            'columnas' => 'required|integer|min:1',
        ];

        $validator = FacadesValidator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect('parqueos/create')
                ->withErrors($validator)
                ->withInput();
        }

        // Si la validación es exitosa, guarda los datos del formulario en la base de datos.
        // ...

        // Crear un nuevo parqueo
        $parqueo = new Parqueo();
        $parqueo->nombre = $request->nombre;
        $parqueo->descripcion = $request->descripcion;
        $parqueo->estado = $request->estado;
        $parqueo->filas = $request->filas;
        $parqueo->columnas = $request->columnas;
        $parqueo->cantidadEspacios = $request->filas * $request->columnas;
        $parqueo->precio = $request->precio;

        // Guardar el objeto Parqueo en la base de datos
        $parqueo->save();

        // Redireccionar a la vista index con el nombre del parqueo y la tabla de botones
        //return view('index', ['nombre' => $nombre]);

        // Crear los espacios para el parqueo
        $filas = $request->filas;
        $columnas = $request->columnas;
        $cont = 1;
        for ($i = 1; $i <= $filas; $i++) {
            for ($j = 1; $j <= $columnas; $j++) {
                $codigo = 'PE-'.$cont;
                $espacios = new Espacio;
                $espacios->codigo = $codigo;
                $espacios->estado = 'disponible';
                $espacios->parqueo_id = $parqueo->id;
                $espacios->save();
                $cont++;
            }
        }

        // Redireccionar a la página de índice de parqueos con un mensaje de éxito
        return redirect()->route('parqueos.index')->with('success', 'Parqueo creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        // Obtener el parqueo desde la base de datos
        $parqueos = Parqueo::find($id);

        // Obtener los espacios del parqueo
        $espacios = Espacio::where('parqueo_id', $parqueos->id)->get();

        // Pasar el parqueo y los espacios a la vista
        return view('index', ['parqueo' => $parqueos, 'espacios' => $espacios]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $parqueo = Parqueo::findOrFail($id);
        $parqueo->delete();
        return redirect()->route('parqueos.index')->with('success', 'Parqueo eliminado exitosamente.');
    }
}

resources/views/parqueos/crear.blade.php
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

@extends('layouts.app')
<link rel="stylesheet" href="{{ asset('/css/espacios.css') }}">
<link rel="stylesheet" href="{{ asset('/css/parqueoIndex.css') }}">
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Registrar parqueo</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <!-- Formulario para registrar el parqueo -->
                            {!! Form::open(array('id' => 'parqueo-form', 'route' => 'parqueos.store','method'=>'POST')) !!}
                            <div class="registrar-Parqueo">
                                <div class ="input-parqueo">
                                    <div class="form-group" style="width: 20%">
                                        {!! Form::label('nombre', 'Nombre del parqueo') !!}
                                        {!! Form::text('nombre', null, array('placeholder' => 'nombre del parqueo','class' => 'form-control', 'required')) !!}
                                        @if ($errors->has('nombre'))
                                            <div class="invalid-feedback">{{ $errors->first('nombre') }}</div>
                                        @endif
                                    </div>
                                    <div class="form-group" style="width: 10%">
                                        {!! Form::label('filas', 'Filas') !!}
                                        {!! Form::number('filas', null, array('placeholder' => '1', 'min'=>'1', 'class' => 'form-control', 'id' => 'filas-input', 'required')) !!}
                                        @if ($errors->has('filas'))
                                            <div class="invalid-feedback">{{ $errors->first('filas') }}</div>
                                        @endif
                                    </div>
                                    <div class="form-group" style="width: 10%">
                                        {!! Form::label('columnas', 'Columnas') !!}
                                        {!! Form::number('columnas', null, array('placeholder' => '1', 'min'=>'1',  'class' => 'form-control', 'id' => 'columnas-input', 'required')) !!}
                                        @if ($errors->has('columnas'))
                                            <div class="invalid-feedback">{{ $errors->first('columnas') }}</div>
                                        @endif
                                    </div>
                                
                                    <div class="form-group" style="width: 17%">
                                        {!! Form::label('estado', 'Estado del parqueo') !!}
                                        {!! Form::select('estado', array('activo' => 'Activo', 'inactivo' => 'Inactivo'), 'activo', array('class' => 'form-control')) !!}
                                    </div>
                                
                                    <div class="form-group" style="width: 25%">
                                        {!! Form::label('descripcion', 'Descripción del parqueo') !!}
                                        {!! Form::textarea('descripcion', isset($parqueo) ? $parqueo->precio : null, array('placeholder' => 'Descripción del parqueo','class' => 'form-control')) !!}
                                    </div>
                                    <div class="form-group" style="width: 10%">
                                    {!! Form::label('precio', 'Precio') !!}
                                    {!! Form::text('precio', null, ['placeholder' => '0 Bs', 'min' => '1', 'class' => 'form-control', 'id' => 'precio-input', 'required']) !!}
                                    @if ($errors->has('precio'))
                                            <div class="invalid-feedback">{{ $errors->first('precio') }}</div>
                                        @endif
                                    </div>
                                </div>
                                <div>
                                    <button type="button" class="btn btn-primary" onclick="generarTabla(document.getElementById('filas-input').value, document.getElementById('columnas-input').value)">Crear</button>
                                </div>
                                <div id="tabla-botones"></div>
                                </div>
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                    <a href="{{ route('parqueos.index') }}" class="btn btn-primary">Cancelar</a>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
<script>
    function generarTabla(filas, columnas) {
    let tabla = '';
    let cont = 1;
    let codigos = ''; // Variable para almacenar los códigos de cada espacio
    for (let i = 1; i <= filas; i++) {
        tabla += '<div class="fila">';
        for (let j = 1; j <= columnas; j++) {
            let codigo = 'PE-'+cont;
            tabla += '<div class="espacio">'+codigo + '</div>';
            codigos += codigo + ','; // Agregar el código al final de la lista de códigos
            cont++;
        }
        tabla += '</div>';
    }
    document.getElementById('tabla-botones').innerHTML = tabla;
    document.getElementById('codigos-input').value = codigos.slice(0, -1); // Asignar la lista de códigos al campo oculto
}

</script>

resources/views/parqueos/index.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="{{ asset('/css/parqueoIndex.css') }}">
@section('content')
<section class="section">
        <div class="section-header">
            <h3 class="page__heading">Parqueos</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <!-- Agregamos el botón de añadir parqueos -->
                            @can('crear-parqueo')
                            <a href="{{ route('parqueos.create') }}" class="btn btn-primary mb-3">Añadir Parqueo</a>
                            @endcan

                            @foreach($parqueos as $parqueo)
                            <div class="card-parqueos">
                                <div class="card-header">
                                    <h5>{{ $parqueo->nombre }}</h5>
                                    
                                    <div class="eliminar-parqueo">
                                        <form method="POST" action="{{ route('parqueos.destroy', ['parqueo' => $parqueo->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            @can('borrar-parqueo')
                                            <button type="submit" class="btn btn-primary">Eliminar</button>
                                            @endcan
                                        </form>
                                    </div>
                                </div>
                                <div class="card-body-info">
                                    <table>
                                        <tr>
                                            <th>ID Parqueo</th>
                                            <th>Código Espacio</th>
                                            <th>Estado</th>
                                        </tr>
                                        @foreach ($parqueo->espacios as $espacio)
                                            <tr>
                                                <td>{{ $espacio->parqueo->id }}</td>
                                                <td>{{ $espacio->codigo }}</td>
                                                <td class="{{ $espacio->estado == 'disponible' ? 'disponible' : 'ocupado' }}">{{ $espacio->estado }}</td>
                                                
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                                    
                            <!-- Agregar más campos según sea necesario -->
                            </div>
                            @endforeach    

                            <!-- Centramos la paginacion a la derecha -->
                          <div class="pagination justify-content-end">
                            
                          </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection